version: '3'

services:
  redis:
    image: redis:latest
    container_name: cache
    ports:
      - '6379:6379'
    networks:
      - blockchain-db
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blockchain-db
      MYSQL_USER: blockchain
      MYSQL_PASSWORD: blockchain
    ports:
      - '3306:3306'
    networks:
      - blockchain-db
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '9600:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - blockchain-db
  blockchain-extractor:
    depends_on:
      - db
      - redis
    image: blockchain-extractor
    restart: always
    ports:
      - '5000:5000'
      - '5001:5001'
    environment:
      BLOCKCHAIN: ETHEREUM
      NETWORK_TYPE: KOVAN
      CLIENT: PARITY
      WS_CONNECTION_STRING: wss://shared-parity-kovan.nodes.deploy.radar.tech/ws?apikey=c5ec2581d1040ce974a38b9b922b05bc0a5ab80572d5d9a6
      RPC_CONNECTION_STRING: https://shared-parity-kovan.nodes.deploy.radar.tech/?apikey=c5ec2581d1040ce974a38b9b922b05bc0a5ab80572d5d9a6
      SERVER_MODE: BOTH
      SERVER_PORT: 5000
      SERVER_SOCKET_PORT: 5001
      SERVER_SOCKET_URL: http://localhost:5001
      REDIS_URL: 'redis'
      MYSQL_URL: 'redis'
    networks:
      - blockchain-db
networks:
  blockchain-db:
volumes:
  db_data:
